<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="6" passed="4">
  <reporter-output>
    <line>
      <![CDATA[About to begin executing Suite Suite]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test Test]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test b]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : test.test1]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : Garima.garima1]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : test.test1]]>
    </line>
    <line>
      <![CDATA[About to begin executing Suite Suite]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test Test]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test b]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : test.test1]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : Garima.garima1]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : Garima.garima1]]>
    </line>
    <line>
      <![CDATA[Test Method resides in com.experitest.auto.test]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[Test Method resides in com.experitest.auto.Garima]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : Garima.garima2]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : Garima.garima2]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : test.test2]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : test.test2]]>
    </line>
    <line>
      <![CDATA[Test Method resides in com.experitest.auto.Garima]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[Test Method resides in com.experitest.auto.test]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : Garima.garima3]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : Garima.garima3]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : test.test3]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : test.test3]]>
    </line>
    <line>
      <![CDATA[Test Method resides in com.experitest.auto.test]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[Test Method resides in com.experitest.auto.Garima]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[About to begin executing Suite Suite]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test Test]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test b]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : test.test1]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : Garima.garima1]]>
    </line>
    <line>
      <![CDATA[About to begin executing following method : SetupClass.teardown]]>
    </line>
    <line>
      <![CDATA[Completed executing following method : SetupClass.teardown]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="62" started-at="2018-07-26T06:33:17Z" finished-at="2018-07-26T06:33:17Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="62" started-at="2018-07-26T06:33:17Z" finished-at="2018-07-26T06:33:17Z">
      <class name="com.experitest.auto.test">
        <test-method status="PASS" signature="test1()[pri:0, instance:com.experitest.auto.test@1e88b3c]" name="test1" duration-ms="31" started-at="2018-07-26T12:03:17Z" finished-at="2018-07-26T12:03:17Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : test.test1]]>
            </line>
            <line>
              <![CDATA[Test Method resides in com.experitest.auto.test]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.experitest.auto.test@1e88b3c]" name="test2" duration-ms="0" started-at="2018-07-26T12:03:17Z" finished-at="2018-07-26T12:03:17Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : test.test2]]>
            </line>
            <line>
              <![CDATA[Test Method resides in com.experitest.auto.test]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="FAIL" signature="test3()[pri:0, instance:com.experitest.auto.test@1e88b3c]" name="test3" duration-ms="16" started-at="2018-07-26T12:03:17Z" finished-at="2018-07-26T12:03:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at com.experitest.auto.test.test3(test.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : test.test3]]>
            </line>
            <line>
              <![CDATA[Test Method resides in com.experitest.auto.test]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- com.experitest.auto.test -->
    </test> <!-- Test -->
    <test name="b" duration-ms="62" started-at="2018-07-26T06:33:17Z" finished-at="2018-07-26T06:33:17Z">
      <class name="com.experitest.auto.Garima">
        <test-method status="PASS" signature="garima1()[pri:0, instance:com.experitest.auto.Garima@14ba872]" name="garima1" duration-ms="31" started-at="2018-07-26T12:03:17Z" finished-at="2018-07-26T12:03:17Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : Garima.garima1]]>
            </line>
            <line>
              <![CDATA[Test Method resides in com.experitest.auto.Garima]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- garima1 -->
        <test-method status="PASS" signature="garima2()[pri:0, instance:com.experitest.auto.Garima@14ba872]" name="garima2" duration-ms="0" started-at="2018-07-26T12:03:17Z" finished-at="2018-07-26T12:03:17Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : Garima.garima2]]>
            </line>
            <line>
              <![CDATA[Test Method resides in com.experitest.auto.Garima]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- garima2 -->
        <test-method status="FAIL" signature="garima3()[pri:0, instance:com.experitest.auto.Garima@14ba872]" name="garima3" duration-ms="16" started-at="2018-07-26T12:03:17Z" finished-at="2018-07-26T12:03:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at com.experitest.auto.Garima.garima3(Garima.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : Garima.garima3]]>
            </line>
            <line>
              <![CDATA[Test Method resides in com.experitest.auto.Garima]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- garima3 -->
      </class> <!-- com.experitest.auto.Garima -->
      <class name="com.experitest.auto.test">
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.experitest.auto.test@1e88b3c]" name="teardown" is-config="true" duration-ms="1" started-at="2018-07-26T12:03:17Z" finished-at="2018-07-26T12:03:17Z">
          <reporter-output>
            <line>
              <![CDATA[Completed executing following method : SetupClass.teardown]]>
            </line>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.experitest.auto.test -->
    </test> <!-- b -->
  </suite> <!-- Suite -->
</testng-results>
